
spring:
  # Database
  datasource:
    url: jdbc:postgresql://localhost:5432/file_sharing
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
#      jdbc-url: jdbc:postgresql://localhost:5432/file_sharing
      driver-class-name: org.postgresql.Driver